-- init.sql

CREATE DATABASE IF NOT EXISTS project DEFAULT CHARACTER SET utf8mb4;
USE project;

CREATE TABLE IF NOT EXISTS jobseeker (
  id VARCHAR(50) PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  password VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  resume LONGBLOB
);

CREATE TABLE IF NOT EXISTS employer (
  id VARCHAR(50) PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  password VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  image_url VARCHAR(255)
);
